sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with docerfile"
  - docker build -t diosamor/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true diosamor/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"
